# -- mode: ruby --
# vi: set ft=ruby :
# vagrant plugin install vagrant-hostmanager

Vagrant.configure("2") do |config|
    config.vm.box = "centos/stream10"
    config.vm.box_version = "20250331.0"

    config.vm.network "private_network", ip: "192.168.10.12"
    config.vm.network "public_network"
    config.vm.hostname = "stream10"

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

    config.vm.provision "shell", inline: <<-SHELL
        sudo dnf upgrade --refresh -y && sudo dnf autoremove -y && sudo dnf clean all
        sudo dnf install httpd -y
        sudo systemctl start httpd
        sudo systemctl enable httpd

        mkdir /tmp/test1
    SHELL

end